use crate::AddressingMode;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Opcode {
    pub code: u8,
    pub bytes: u8,
    pub base_cycles: u8,
    pub mode: AddressingMode,
    pub official: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct OpcodeDefinition {
    pub(crate) base_cycles: u8,
    pub(crate) mode: AddressingMode,
    pub(crate) official: bool,
    pub(crate) indexed_read_page_penalty: bool,
}

const fn opcode_definition(
    base_cycles: u8,
    mode: AddressingMode,
    official: bool,
    indexed_read_page_penalty: bool,
) -> OpcodeDefinition {
    OpcodeDefinition {
        base_cycles,
        mode,
        official,
        indexed_read_page_penalty,
    }
}

macro_rules! op {
    ($cycles:literal, $mode:ident, $official:literal, $page_cross:literal) => {
        opcode_definition($cycles, AddressingMode::$mode, $official, $page_cross)
    };
}

const OPCODES: [OpcodeDefinition; 256] = [
    op!(7, Implied, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(0, Implied, false, false),
    op!(8, IndexedIndirect, false, false),
    op!(3, ZeroPage, false, false),
    op!(3, ZeroPage, true, false),
    op!(5, ZeroPage, true, false),
    op!(5, ZeroPage, false, false),
    op!(3, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Accumulator, true, false),
    op!(2, Immediate, false, false),
    op!(4, Absolute, false, false),
    op!(4, Absolute, true, false),
    op!(6, Absolute, true, false),
    op!(6, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(8, IndirectIndexed, false, false),
    op!(4, ZeroPageX, false, false),
    op!(4, ZeroPageX, true, false),
    op!(6, ZeroPageX, true, false),
    op!(6, ZeroPageX, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, false, false),
    op!(7, AbsoluteY, false, false),
    op!(4, AbsoluteX, false, true),
    op!(4, AbsoluteX, true, true),
    op!(7, AbsoluteX, true, false),
    op!(7, AbsoluteX, false, false),
    op!(6, Absolute, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(0, Implied, false, false),
    op!(8, IndexedIndirect, false, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(5, ZeroPage, true, false),
    op!(5, ZeroPage, false, false),
    op!(4, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Accumulator, true, false),
    op!(2, Immediate, false, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(6, Absolute, true, false),
    op!(6, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(8, IndirectIndexed, false, false),
    op!(4, ZeroPageX, false, false),
    op!(4, ZeroPageX, true, false),
    op!(6, ZeroPageX, true, false),
    op!(6, ZeroPageX, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, false, false),
    op!(7, AbsoluteY, false, false),
    op!(4, AbsoluteX, false, true),
    op!(4, AbsoluteX, true, true),
    op!(7, AbsoluteX, true, false),
    op!(7, AbsoluteX, false, false),
    op!(6, Implied, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(0, Implied, false, false),
    op!(8, IndexedIndirect, false, false),
    op!(3, ZeroPage, false, false),
    op!(3, ZeroPage, true, false),
    op!(5, ZeroPage, true, false),
    op!(5, ZeroPage, false, false),
    op!(3, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Accumulator, true, false),
    op!(2, Immediate, false, false),
    op!(3, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(6, Absolute, true, false),
    op!(6, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(8, IndirectIndexed, false, false),
    op!(4, ZeroPageX, false, false),
    op!(4, ZeroPageX, true, false),
    op!(6, ZeroPageX, true, false),
    op!(6, ZeroPageX, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, false, false),
    op!(7, AbsoluteY, false, false),
    op!(4, AbsoluteX, false, true),
    op!(4, AbsoluteX, true, true),
    op!(7, AbsoluteX, true, false),
    op!(7, AbsoluteX, false, false),
    op!(6, Implied, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(0, Implied, false, false),
    op!(8, IndexedIndirect, false, false),
    op!(3, ZeroPage, false, false),
    op!(3, ZeroPage, true, false),
    op!(5, ZeroPage, true, false),
    op!(5, ZeroPage, false, false),
    op!(4, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Accumulator, true, false),
    op!(2, Immediate, false, false),
    op!(5, Indirect, true, false),
    op!(4, Absolute, true, false),
    op!(6, Absolute, true, false),
    op!(6, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(8, IndirectIndexed, false, false),
    op!(4, ZeroPageX, false, false),
    op!(4, ZeroPageX, true, false),
    op!(6, ZeroPageX, true, false),
    op!(6, ZeroPageX, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, false, false),
    op!(7, AbsoluteY, false, false),
    op!(4, AbsoluteX, false, true),
    op!(4, AbsoluteX, true, true),
    op!(7, AbsoluteX, true, false),
    op!(7, AbsoluteX, false, false),
    op!(2, Immediate, false, false),
    op!(6, IndexedIndirect, true, false),
    op!(2, Immediate, false, false),
    op!(6, IndexedIndirect, false, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, false, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, false, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, false, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(6, IndirectIndexed, true, false),
    op!(0, Implied, false, false),
    op!(6, IndirectIndexed, false, false),
    op!(4, ZeroPageX, true, false),
    op!(4, ZeroPageX, true, false),
    op!(4, ZeroPageY, true, false),
    op!(4, ZeroPageY, false, false),
    op!(2, Implied, true, false),
    op!(5, AbsoluteY, true, false),
    op!(2, Implied, true, false),
    op!(5, AbsoluteY, false, false),
    op!(5, AbsoluteX, false, false),
    op!(5, AbsoluteX, true, false),
    op!(5, AbsoluteY, false, false),
    op!(5, AbsoluteY, false, false),
    op!(2, Immediate, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(2, Immediate, true, false),
    op!(6, IndexedIndirect, false, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, false, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, false, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(5, IndirectIndexed, false, true),
    op!(4, ZeroPageX, true, false),
    op!(4, ZeroPageX, true, false),
    op!(4, ZeroPageY, true, false),
    op!(4, ZeroPageY, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, false, true),
    op!(4, AbsoluteX, true, true),
    op!(4, AbsoluteX, true, true),
    op!(4, AbsoluteY, true, true),
    op!(4, AbsoluteY, false, true),
    op!(2, Immediate, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(2, Immediate, false, false),
    op!(8, IndexedIndirect, false, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(5, ZeroPage, true, false),
    op!(5, ZeroPage, false, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, false, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(6, Absolute, true, false),
    op!(6, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(8, IndirectIndexed, false, false),
    op!(4, ZeroPageX, false, false),
    op!(4, ZeroPageX, true, false),
    op!(6, ZeroPageX, true, false),
    op!(6, ZeroPageX, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, false, false),
    op!(7, AbsoluteY, false, false),
    op!(4, AbsoluteX, false, true),
    op!(4, AbsoluteX, true, true),
    op!(7, AbsoluteX, true, false),
    op!(7, AbsoluteX, false, false),
    op!(2, Immediate, true, false),
    op!(6, IndexedIndirect, true, false),
    op!(2, Immediate, false, false),
    op!(8, IndexedIndirect, false, false),
    op!(3, ZeroPage, true, false),
    op!(3, ZeroPage, true, false),
    op!(5, ZeroPage, true, false),
    op!(5, ZeroPage, false, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, true, false),
    op!(2, Implied, true, false),
    op!(2, Immediate, false, false),
    op!(4, Absolute, true, false),
    op!(4, Absolute, true, false),
    op!(6, Absolute, true, false),
    op!(6, Absolute, false, false),
    op!(2, Relative, true, false),
    op!(5, IndirectIndexed, true, true),
    op!(0, Implied, false, false),
    op!(8, IndirectIndexed, false, false),
    op!(4, ZeroPageX, false, false),
    op!(4, ZeroPageX, true, false),
    op!(6, ZeroPageX, true, false),
    op!(6, ZeroPageX, false, false),
    op!(2, Implied, true, false),
    op!(4, AbsoluteY, true, true),
    op!(2, Implied, false, false),
    op!(7, AbsoluteY, false, false),
    op!(4, AbsoluteX, false, true),
    op!(4, AbsoluteX, true, true),
    op!(7, AbsoluteX, true, false),
    op!(7, AbsoluteX, false, false),
];

pub fn opcode(byte: u8) -> Opcode {
    let definition = definition(byte);
    Opcode {
        code: byte,
        bytes: definition.mode.operand_bytes() + 1,
        base_cycles: definition.base_cycles,
        mode: definition.mode,
        official: definition.official,
    }
}

pub(crate) const fn definition(byte: u8) -> OpcodeDefinition {
    OPCODES[byte as usize]
}
